[global]
keyboard = "en-us"
country = "us"
fqdn = "pve1.local"
mailto = "mail@exsample.local"
timezone = "Europe/Moscow"
root_password = "password"

[network]
source = "from-answer"
cidr = "192.168.8.100/24"
dns = "192.168.8.1"
gateway = "192.168.8.1"

filter.ID_NET_NAME = "eno1"

[disk-setup]
filesystem = "ext4"
lvm.swapsize = 32768
lvm.maxvz = 0

disk_list = ['sda']
